### ISSUE TITLE
terraform.exe import yandex_resourcemanager_folder_iam_member CRASH

### ISSUE THREAD

**Issue by v-bus** [yandex-cloud/terraform-provider-yandex#130]
Что делал:
через терраформ создал сервисный аккаунт, была ошибка по `yandex_resourcemanager_folder_iam_member ` что недостаточно прав. Зашел на веб-консоль, кнопками натыкал созданному терраформом сервис аккаунту `storage.admin` и хотел его импортировать, как написано в документации:

>  terraform import yandex_resourcemanager_folder_iam_member.my_project "folder_id viewer foo@example.com"

строка моя:

>  terraform.exe import yandex_resourcemanager_folder_iam_member.sa-storage-admin "b1gj60agbkfo2a79f027 storage.admin terraformsa"

получил трейс:

```bash
yandex_resourcemanager_folder_iam_member.sa-storage-admin: Importing from ID "b1gj60agbkfo2a79f027 storage.admin terraformsa"...
yandex_resourcemanager_folder_iam_member.sa-storage-admin: Import prepared!
  Prepared yandex_resourcemanager_folder_iam_member for import
yandex_resourcemanager_folder_iam_member.sa-storage-admin: Refreshing state... [id=b1gj60agbkfo2a79f027/storage.admin/terraformsa]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range [1] with length 1
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: goroutine 37 [running]:
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: github.com/yandex-cloud/terraform-provider-yandex/yandex.roleMemberToAccessBinding(0xc0002901b0, 0xd, 0xc0002901a0, 0xb, 0xc000caeab0)
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:      github.com/yandex-cloud/terraform-provider-yandex/yandex/utils.go:257 +0x187
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: github.com/yandex-cloud/terraform-provider-yandex/yandex.getResourceIamMember(0xc000314620, 0xc000b38600)
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:      github.com/yandex-cloud/terraform-provider-yandex/yandex/iam_member.go:95 +0xd8
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: github.com/yandex-cloud/terraform-provider-yandex/yandex.resourceIamMemberRead.func1(0xc000314620, 0x16dc060, 0xc000b38600, 0xc000314620, 0x0)
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:      github.com/yandex-cloud/terraform-provider-yandex/yandex/iam_member.go:133 +0xae
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000850680, 0xc00021f310, 0x16dc060, 0xc000b38600, 0xc000cd40f0, 0x0, 0x0)
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:      github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/resource.go:455 +0x120
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000210320, 0x1c2b160, 0xc000cb21e0, 0xc00021e870, 0xc000210320, 0xc000cb21e0, 0xc000921b88)
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:      github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/helper/plugin/grpc_provider.go:525 +0x3df
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1894140, 0xc000210320, 0x1c2b160, 0xc000cb21e0, 0xc00007c840, 0x0, 0x1c2b160, 0xc000cb21e0, 0xc000cc0000, 0xce)
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:      github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x21e
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00081a000, 0x1c3ae60, 0xc00006cf00, 0xc000b3d400, 0xc0007f34a0, 0x2ba27d0, 0x0, 0x0, 0x0)
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:      google.golang.org/grpc@v1.28.0/server.go:1082 +0x511
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: google.golang.org/grpc.(*Server).handleStream(0xc00081a000, 0x1c3ae60, 0xc00006cf00, 0xc000b3d400, 0x0)
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:      google.golang.org/grpc@v1.28.0/server.go:1405 +0xcd2
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002121b0, 0xc00081a000, 0x1c3ae60, 0xc00006cf00, 0xc000b3d400)
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:      google.golang.org/grpc@v1.28.0/server.go:746 +0xa8
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-28T18:55:22.261+0300 [DEBUG] plugin.terraform-provider-yandex_v0.49.0.exe:      google.golang.org/grpc@v1.28.0/server.go:744 +0xa8
2021/01/28 18:55:22 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/01/28 18:55:22 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/01/28 18:55:22 [TRACE] [walkImport] Exiting eval tree: import yandex_resourcemanager_folder_iam_member.sa-storage-admin result
2021/01/28 18:55:22 [TRACE] vertex "import yandex_resourcemanager_folder_iam_member.sa-storage-admin result": visit complete
2021/01/28 18:55:22 [TRACE] vertex "yandex_resourcemanager_folder_iam_member.sa-storage-admin (import id \"b1gj60agbkfo2a79f027 storage.admin terraformsa\")": dynamic subgraph encountered errors
2021/01/28 18:55:22 [TRACE] vertex "yandex_resourcemanager_folder_iam_member.sa-storage-admin (import id \"b1gj60agbkfo2a79f027 storage.admin terraformsa\")": visit complete
2021/01/28 18:55:22 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/yandex-cloud/yandex\"] (close)" errored, so skipping
2021/01/28 18:55:22 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/28 18:55:22 [DEBUG] DELETE https://gitlab.alfastrah.ru/api/v4/projects/1538/terraform/state/ansible_masterhost_bushminvv/lock
2021-01-28T18:55:22.275+0300 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/yandex-cloud/yandex/0.49.0/windows_amd64/terraform-provider-yandex_v0.49.0.exe pid=61500 error="exit status 2"
2021-01-28T18:55:22.433+0300 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

Судя по ушам - проблемы с терраформ SDK схемой, по коду норм должно проходить.

Теперь о конфигурации:
ОС - Винда 10 х64
Консолька - MINGW64

```bash
$ terraform.exe version
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/yandex-cloud/yandex v0.49.0

```

Код

```
#################################################################################
## from https://github.com/yandex-cloud/terraform-provider-yandex/issues/121
#################################################################################

## Create SA
resource "yandex_iam_service_account" "sa" {
  folder_id = var.yc_folder_id
  name      = "terraformsa"
}

## Grant permissions 
resource "yandex_resourcemanager_folder_iam_member" "sa-storage-admin" {
  folder_id = var.yc_folder_id
  role      = "storage.admin"
  member    = "serviceAccount:${yandex_iam_service_account.sa.id}"
}

## Create Static Access Keys
resource "yandex_iam_service_account_static_access_key" "sa-static-key" {
  service_account_id = yandex_iam_service_account.sa.id
  description        = "static access key for object storage"
}

```

**Comment by apilikov** [comment]
Thanks for posting this!

We are working on the issue. As soon as it is fixed we'll let you know.

Thank you!

**Comment by apilikov** [comment]
This issue has been fixed in latest release.
