### ISSUE TITLE
Error: The terraform-provider-yandex_v0.76.0 plugin crashed!

### ISSUE THREAD

**Issue by OksanaChurkina** [yandex-cloud/terraform-provider-yandex#272]
when executing terraforms the plan happens Error: The terraform-provider-yandex_v0.76.0 plugin crashed!

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x2424b46]

goroutine 27 [running]:
github.com/yandex-cloud/terraform-provider-yandex/yandex.flattenYandexYDBDatabaseServerless(0xc0001b1e00, 0x0, 0x0, 0x0)
        github.com/yandex-cloud/terraform-provider-yandex/yandex/resource_yandex_ydb_database_serverless.go:162 +0x26
github.com/yandex-cloud/terraform-provider-yandex/yandex.resourceYandexYDBDatabaseServerlessRead(0xc0001b1e00, 0x276b220, 0xc000119e60, 0x3f09f00, 0xc00007c480)
        github.com/yandex-cloud/terraform-provider-yandex/yandex/resource_yandex_ydb_database_serverless.go:158 +0x89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000b10c40, 0x2d34b38, 0xc00057ad80, 0xc0001b1e00, 0x276b220, 0xc000119e60, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:346 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000b10c40, 0x2d34b38, 0xc00057ad80, 0xc000b0bd40, 0x276b220, 0xc000119e60, 0xc00000ebd0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:635 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00032ccc0, 0x2d34b38, 0xc00057ad80, 0xc00057adc0, 0x2a52956, 0x12, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/grpc_provider.go:576 +0x47d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000f0a180, 0x2d34be0, 0xc00057ad80, 0xc0000a4de0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x322
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x29969a0, 0xc000f0a180, 0x2d34be0, 0xc00040f230, 0xc0000a4d80, 0x0, 0x2d34be0, 0xc00040f230, 0xc000067180, 0x304)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000486fc0, 0x2d41178, 0xc000af21a0, 0xc0000245a0, 0xc000f085a0, 0x3eb50f0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000486fc0, 0x2d41178, 0xc000af21a0, 0xc0000245a0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00030c270, 0xc000486fc0, 0x2d41178, 0xc000af21a0, 0xc0000245a0)
        google.golang.org/grpc@v1.45.0/server.go:921 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x1fd

Error: The terraform-provider-yandex_v0.76.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by shmel1k** [comment]
Hello, @OksanaChurkina !

We've taken your report and will fix the error soon. It would be great if you send your resource configuration in order we can try to reproduce the error. Thanks in advance!

**Comment by shmel1k** [comment]
https://github.com/yandex-cloud/terraform-provider-yandex/pull/273
