### ISSUE TITLE
Error: The terraform-provider-yandex_v0.101.0 plugin crashed!

### ISSUE THREAD

**Issue by ddimasik** [yandex-cloud/terraform-provider-yandex#392]
I'm creating ALB and after `terraform apply` and `yes` got this stacktrace

```
% terraform --version
Terraform v1.5.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/http v3.4.0
+ provider registry.terraform.io/yandex-cloud/yandex v0.101.0
```

```
Stack trace from the terraform-provider-yandex_v0.101.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 146 [running]:
github.com/yandex-cloud/terraform-provider-yandex/yandex.expandALBLogOptions(0x2e19e80?)
        github.com/yandex-cloud/terraform-provider-yandex/yandex/alb_structures.go:618 +0x268
github.com/yandex-cloud/terraform-provider-yandex/yandex.resourceYandexALBLoadBalancerCreate(0xc001796d80, {0x2c25f00?, 0xc000f10580})
        github.com/yandex-cloud/terraform-provider-yandex/yandex/resource_yandex_alb_load_balancer.go:441 +0x5d2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x32364e0?, {0x32364e0?, 0xc0016aa8d0?}, 0xd?, {0x2c25f00?, 0xc000f10580?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:766 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00051b420, {0x32364e0, 0xc0016aa8d0}, 0xc0016b0d00, 0xc0016ca180, {0x2c25f00, 0xc000f10580})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001368e8, {0x32364e0?, 0xc0016aa6f0?}, 0xc001647d10)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/grpc_provider.go:1027 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x3240a08?, 0xc0001368e8?}}, {0x32364e0, 0xc0016aa6f0}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5to6server/tf5to6server.go:37 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc000c95ad0, 0xc0006cd790, 0xc000c95b00, 0xc000c95b30, {0xc000134a80, 0x2, 0x2}}, {0x32364e0?, 0xc0016aa3c0?}, 0xc001647cc0)
        github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf6muxserver/mux_server_ApplyResourceChange.go:30 +0x139
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0009de8c0, {0x32364e0?, 0xc00168fb90?}, 0xc0015f6e70)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:819 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x2e19d20?, 0xc0009de8c0}, {0x32364e0, 0xc00168fb90}, 0xc0015f6e00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005c4f00, {0x323f1e0, 0xc00051e680}, 0xc001699c20, 0xc000d4d980, 0x4a7c4c0, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0005c4f00, {0x323f1e0, 0xc00051e680}, 0xc001699c20, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x18c

Error: The terraform-provider-yandex_v0.101.0 plugin crashed!
```

**Comment by KoDA82** [comment]
Hi, sorry for the delay in processing.
Is this issue still relevant?

**Comment by ddimasik** [comment]
in 102 it started to work, thank you
