### ISSUE TITLE
OpenSearch: yandex provider crashed again

### ISSUE THREAD

**Issue by sharovmerk** [yandex-cloud/terraform-provider-yandex#423]
I have terraform module that creates opensearch. After the fix related to dashboard it finally started to work, but when I ran terraform for the second time (without any code change), yandex provider crashed. Please, fix OpenSearch resource. It's painful for more than 3 months.

```
  ~ resource "yandex_mdb_opensearch_cluster" "main" {
        id                  = "XXX"
        name                = "XXX"
        # (11 unchanged attributes hidden)

      ~ config {
            # (2 unchanged attributes hidden)

          - dashboards {
            }

          ~ opensearch {
                # (1 unchanged attribute hidden)

              - node_groups {
                  - assign_public_ip = true -> null
                  - hosts_count      = 2 -> null
                  - name             = "default-os-data" -> null
                  - roles            = [
                      - "DATA",
                    ] -> null
                  - subnet_ids       = [
                      - "XXX",
                      - "XXX",
                      - "XXX",
                    ] -> null
                  - zone_ids         = [
                      - "ru-central1-a",
                      - "ru-central1-b",
                      - "ru-central1-d",
                    ] -> null

                  - resources {
                      - disk_size          = 64424509440 -> null
                      - disk_type_id       = "network-ssd" -> null
                      - resource_preset_id = "s3-c2-m8" -> null
                    }
                }
              - node_groups {
                  - assign_public_ip = true -> null
                  - hosts_count      = 5 -> null
                  - name             = "default-os-manager" -> null
                  - roles            = [
                      - "MANAGER",
                    ] -> null
                  - subnet_ids       = [
                      - "XXX",
                      - "XXX",
                      - "XXX",
                    ] -> null
                  - zone_ids         = [
                      - "ru-central1-a",
                      - "ru-central1-b",
                      - "ru-central1-d",
                    ] -> null

                  - resources {
                      - disk_size          = 64424509440 -> null
                      - disk_type_id       = "network-ssd" -> null
                      - resource_preset_id = "s3-c2-m8" -> null
                    }
                }
              + node_groups {
                  + assign_public_ip = true
                  + hosts_count      = 2
                  + name             = "default-os-data"
                  + roles            = [
                      + "data",
                    ]
                  + subnet_ids       = [
                      + "XXX",
                      + "XXX",
                      + "XXX",
                    ]
                  + zone_ids         = [
                      + "ru-central1-a",
                      + "ru-central1-b",
                      + "ru-central1-d",
                    ]

                  + resources {
                      + disk_size          = 64424509440
                      + disk_type_id       = "network-ssd"
                      + resource_preset_id = "s3-c2-m8"
                    }
                }
              + node_groups {
                  + assign_public_ip = true
                  + hosts_count      = 5
                  + name             = "default-os-manager"
                  + roles            = [
                      + "manager",
                    ]
                  + subnet_ids       = [
                      + "XXX",
                      + "XXX",
                      + "XXX",
                    ]
                  + zone_ids         = [
                      + "ru-central1-a",
                      + "ru-central1-b",
                      + "ru-central1-d",
                    ]

                  + resources {
                      + disk_size          = 64424509440
                      + disk_type_id       = "network-ssd"
                      + resource_preset_id = "s3-c2-m8"
                    }
                }
            }
        }

        # (1 unchanged block hidden)
    }
```
    
    
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.seed.module.opensearch["os-01"].yandex_mdb_opensearch_cluster.main: Modifying... [id=XXX]
╷
│ Warning: AWS account ID not found for provider
│ 
│   with module.seed.provider["registry.terraform.io/hashicorp/aws"],
│   on .terraform/modules/seed/00-versions.tf line 20, in provider "aws":
│   20: provider "aws" {
│ 
│ See
│ https://registry.terraform.io/providers/hashicorp/aws/latest/docs#skip_requesting_account_id
│ for implications.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-yandex_v0.112.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x26db9f1]

goroutine 129 [running]:
github.com/yandex-cloud/terraform-provider-yandex/yandex.updateDashboardsNodeGroupsParams(0xc0016e7000, {0x2cf13a0, 0xc000f9adc0})
        github.com/yandex-cloud/terraform-provider-yandex/yandex/resource_yandex_mdb_opensearch_cluster.go:702 +0x251
github.com/yandex-cloud/terraform-provider-yandex/yandex.resourceYandexMDBOpenSearchClusterUpdate(0xc0016e7000, {0x2cf13a0, 0xc000f9adc0})
        github.com/yandex-cloud/terraform-provider-yandex/yandex/resource_yandex_mdb_opensearch_cluster.go:569 +0x65
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x332bc80?, {0x332bc80?, 0xc0014f6150?}, 0xd?, {0x2cf13a0?, 0xc000f9adc0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:800 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000e23a40, {0x332bc80, 0xc0014f6150}, 0xc000bc9450, 0xc0003bde00, {0x2cf13a0, 0xc000f9adc0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:919 +0x845
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00019ef18, {0x332bc80?, 0xc001597f50?}, 0xc000b963c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/grpc_provider.go:1027 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x33364c8?, 0xc00019ef18?}}, {0x332bc80, 0xc001597f50}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5to6server/tf5to6server.go:37 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc000e69200, 0xc001183c50, 0xc000e69230, 0xc000e69260, {0xc000d0ec80, 0x2, 0x2}}, {0x332bc80?, 0xc001597c20?}, 0xc000b96370)
        github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf6muxserver/mux_server_ApplyResourceChange.go:30 +0x139
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000b5cb40, {0x332bc80?, 0xc001597230?}, 0xc0012a7d50)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:819 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x2ef8260?, 0xc000b5cb40}, {0x332bc80, 0xc001597230}, 0xc000c1f800, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000ba3200, {0x332bc80, 0xc001597170}, {0x3334c80, 0xc000534680}, 0xc0014eca20, 0xc000f150b0, 0x4c34a60, 0x0)
        google.golang.org/grpc@v1.61.0/server.go:1385 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc000ba3200, {0x3334c80, 0xc000534680}, 0xc0014eca20)
        google.golang.org/grpc@v1.61.0/server.go:1796 +0x1031
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.61.0/server.go:1029 +0x91
created by google.golang.org/grpc.(*Server).serveStreams.func2
        google.golang.org/grpc@v1.61.0/server.go:1040 +0x145

Error: The terraform-provider-yandex_v0.112.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by sharovmerk** [comment]
Linked issues:
https://github.com/yandex-cloud/terraform-provider-yandex/issues/412
https://github.com/yandex-cloud/terraform-provider-yandex/issues/409
https://github.com/yandex-cloud/terraform-provider-yandex/issues/410
https://github.com/yandex-cloud/terraform-provider-yandex/issues/403

**Comment by sharovmerk** [comment]
@saiks24 please, check it. It's really painful to work with OpenSearch via Terraform.

**Comment by vanekmc1** [comment]
The same issue. 
Creating opensearch without dashboard works.
However, when applying the same terraform code, change to dashboard is planned and provider crashes.
``` 
# yandex_mdb_opensearch_cluster.main will be updated in-place
  ~ resource "yandex_mdb_opensearch_cluster" "main" {
        id                  = "************"
        name                = "****************"
        # (9 unchanged attributes hidden)
      ~ config {
            # (2 unchanged attributes hidden)
          - dashboards {
            }
            # (1 unchanged block hidden)
        }
        # (1 unchanged block hidden)
    }
Plan: 1 to add, 1 to change, 0 to destroy.
yandex_mdb_opensearch_cluster.main: Modifying... [id=***********]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-yandex_v0.113.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1b0abb1]
goroutine 26 [running]:
github.com/yandex-cloud/terraform-provider-yandex/yandex.updateDashboardsNodeGroupsParams(0xc001429f00, {0x212f6a0, 0xc000887a20})
	github.com/yandex-cloud/terraform-provider-yandex/yandex/resource_yandex_mdb_opensearch_cluster.go:702 +0x251
github.com/yandex-cloud/terraform-provider-yandex/yandex.resourceYandexMDBOpenSearchClusterUpdate(0xc001429f00, {0x212f6a0, 0xc000887a20})
	github.com/yandex-cloud/terraform-provider-yandex/yandex/resource_yandex_mdb_opensearch_cluster.go:569 +0x65
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x2775900?, {0x2775900?, 0xc000ef52f0?}, 0xd?, {0x212f6a0?, 0xc000887a20?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:800 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000cb0e00, {0x2775900, 0xc000ef52f0}, 0xc000a6b380, 0xc0009dcf00, {0x212f6a0, 0xc000887a20})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:919 +0x845
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000010378, {0x2775900?, 0xc000ef5110?}, 0xc00112d630)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/grpc_provider.go:1027 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x27802c8?, 0xc000010378?}}, {0x2775900, 0xc000ef5110}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5to6server/tf5to6server.go:37 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc000b4f470, 0xc00108f950, 0xc000b4f4a0, 0xc000b4f4d0, {0xc0009f81a0, 0x2, 0x2}}, {0x2775900?, 0xc000ef4de0?}, 0xc00112d5e0)
	github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf6muxserver/mux_server_ApplyResourceChange.go:30 +0x139
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00052e460, {0x2775900?, 0xc000e3d5f0?}, 0xc00052c070)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:819 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x233c520?, 0xc00052e460}, {0x2775900, 0xc000e3d5f0}, 0xc0009dc000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008cb200, {0x2775900, 0xc000e3d560}, {0x277ea20, 0xc000007d40}, 0xc000f0f440, 0xc0008cc2d0, 0x40a7080, 0x0)
	google.golang.org/grpc@v1.62.1/server.go:1386 +0xe69
google.golang.org/grpc.(*Server).handleStream(0xc0008cb200, {0x277ea20, 0xc000007d40}, 0xc000f0f440)
	google.golang.org/grpc@v1.62.1/server.go:1797 +0x1051
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.62.1/server.go:1027 +0x91
created by google.golang.org/grpc.(*Server).serveStreams.func2
	google.golang.org/grpc@v1.62.1/server.go:1038 +0x145
Error: The terraform-provider-yandex_v0.113.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by sharovmerk** [comment]
@opportunity356 @2x4ever @saiks24 check it , pls

**Comment by saiks24** [comment]
Hi, @sharovmerk! 
Issue should be resolved with the last release.
https://github.com/yandex-cloud/terraform-provider-yandex/releases/tag/v0.115.0
